name:                vmanager
version:             0.1.0.0
github:              "p3rsik/vmanager"
license:             BSD3
author:              "Yarik"
maintainer:          "yroslav541@gmail.com"
copyright:           "2020 Yarik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/p3rsik/vmanager#readme>

dependencies:
- base >= 4.7 && < 5
- foundation
- basement
- fused-effects
- ghc-prim

library:
  source-dirs: src
  ghc-options:
  - -Wall
  default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude

executables:
  vmanager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - vmanager
    default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude

tests:
  vmanager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vmanager
