on: [push, pull_request]
name: Tests

jobs:
  manager-test:
    name: Stack test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: mstksg/setup-stack@v1
      - run: stack test