on: [push, pull_request]
name: Tests

jobs:
  manager-test:
    name: Haskell GHC ${{ matrix.ghc }} && Stack ${{ matrix.stack }} test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.10.1'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test